name: Pipeline de Producao

env:
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  

on:
  push:
    branches:
      - main


jobs:

  job1:
    name: CI - Build e criação do artefato
    runs-on: ubuntu-latest
    steps:
      - name: Pegar código do Repositório
        uses: actions/chekout@v3

      - name: Instalando pacotes do npm
        run: npm install

      - name: Gerando documentação do swagger.json
        run: npm run autoDoc

      - name: Apagando pasa node_modules
        run: rm -rf node_modules

      - name: Apagando pasta .git
        run: rm -rf .git

      - name: Arquivos e pastas
        run: ls

      - name: Criando  artefato ZIP do código buildado
        uses: actions/upload-artifct@v3
        with:
          name: artefato
          retention-days: 1
          path: ./


  job2:
    name: CD - Deploy na Vercel
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Baixando Artefato do código buildado
        uses: actions/download-artifact@v3
        with:
          name: artefato
        
      - name: Instalando pacotes do npm
        run: npm install

      - name: Arquivos e pastas do artefato
        run: ls

      - name: Instalar CLI da Vercel
        run: npm install --global vercel@latest

      - name: Buscanso informações de ambiente na Vercel
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Buildando artefatos
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy do artefato do projeto na Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

